added

diff --git a/.github/workflows/sample-workflow.yml b/.github/workflows/sample-workflow.yml
--- a/.github/workflows/sample-workflow.yml
+++ b/.github/workflows/sample-workflow.yml
@@ -13,6 +13,9 @@ jobs:
         environment: [dev, test]  # List all environments here
 
     environment: ${{ matrix.environment }}
+    
+    env:
+      PROJECT_NAME: test-project-ef-internal-03
 
     steps:
       - name: Checkout code
@@ -49,18 +52,44 @@ jobs:
           echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV
 
       - name: Call GET endpoint to check resource
-          id: get_project
-          shell: bash
-          run: |
-            RESOURCE_URL="$test.com/eventservice/controller/v1/projects/test-project-ef-internal-03"
-            echo "URL for get call: $RESOURCE_URL"
-            echo "Checking if resource exists..."
-            STATUS_CODE=$(curl -s -o response.json -w "%{http_code}" -X GET "$RESOURCE_URL" \
-              -H "Authorization: Bearer $ACCESS_TOKEN" \
-              -H "Accept: application/json")
+        id: get_project
+        shell: bash
+        run: |
+          RESOURCE_URL="$EFS_HOST/eventservice/controller/v1/projects/$PROJECT_NAME"
+          
+          echo "Checking if resource exists..."
+          STATUS_CODE=$(curl -s -o response.json -w "%{http_code}" -X GET "$RESOURCE_URL" \
+            -H "Authorization: Bearer $ACCESS_TOKEN" \
+            -H "Accept: application/json")
 
-            echo "GET request returned status: $STATUS_CODE"
-            echo "status=$STATUS_CODE" >> $GITHUB_OUTPUT
+          echo "GET request returned status: $STATUS_CODE"
+          echo "status=$STATUS_CODE" >> $GITHUB_OUTPUT
+
+      - name: Create resource if not found (POST)
+        id: create_project
+        if: steps.get_project.outputs.status == '404'
+        shell: bash
+        run: |
+          RESOURCE_URL="$EFS_HOST/eventservice/controller/v1/project
+
+          echo "Resource not found. Creating..."
+
+          curl -X POST "$RESOURCE_URL" \
+            -H "Authorization: Bearer $ACCESS_TOKEN" \
+            -H "Content-Type: application/json" \
+            -d @src/main/resources/project.json'
+
+      - name: If Project creation failed
+        if: steps.create_project.outputs.status != '201'
+        run: |
+          echo "❌ Resource creation failed. Stopping workflow."
+          exit 1
+      
+      - name: If Project creation success
+        if: steps.create_project.outputs.status == '201'
+        run: |
+          echo "✅ Resource creation succeeded. Proceeding with next steps..."
+          # Add follow-up commands here
 
 
 
